### ISSUE TITLE
Избавляемся от карточки проекта

### ISSUE THREAD

**Issue by sintsov** [SGolenzovskiy/twbs#1]
Карточка проекта нам не требуется, поэтому предлагаю сделать формулировку (референцию) не обычной ссылкой, а пунктирной, и при нажатие на нее должен раскрываться список формулировок, например как на картинке:

![image](https://cloud.githubusercontent.com/assets/7813708/16532508/0bebeff2-3fdb-11e6-9f69-85bb4b4e8d21.png)

Согласно постановке задачи их будет ограниченное кол-во 4-5 штук. 
Кроме перетаскивания, отсюда надо предусмотреть возможность отредактировать существующую формулировку, удалить и добавить еще одну. При повторном нажатие на ссылку, список должен скрываться.

**Comment by Golenzovskiy** [comment]
https://github.com/SGolenzovskiy/twbs/commit/d9353fbd56672d9676bdadac32e9e021e45c0770
