### ISSUE TITLE
Фильтр по облаку тегов

### ISSUE THREAD

**Issue by sintsov** [SGolenzovskiy/twbs#10]
Реализуем простую фильтрацию. У каждого лейбла добавляем тег data-tag='<идентификатор тега>', а для каждого проекта в поиске добавляем data-tags='["тег 1", "тег2"]' то есть массив тегов для этого проекта. 

Далее вешаем класс на каждый лейбл, например js-tag-filter
Он должен по клику получать все элементы содержащие data-tags и проверять содержимое массива на совпадение, и если совпадения не произошло скрываем эту строку.

**Comment by Golenzovskiy** [comment]
0d4f1d9d023a569c9dcbcd1e4610b4128b0ff4c1

**Comment by Golenzovskiy** [comment]
Determining active tag:
https://github.com/SGolenzovskiy/twbs/commit/be93418e23437c0defb064a25e3f52bd213eb840
