### ISSUE TITLE
Добавить кнопку удаление проекта

### ISSUE THREAD

**Issue by sintsov** [SGolenzovskiy/twbs#11]
Вполне допускаю такая кнопка нужна, думаю она должна быть в блоке редактирование/добавления проекта. Как лучше сделать остается на твое усмотрение. 

Требуется сразу добавить всплывашку, вы уверены, что хотите удалить проект. Это можно было бы сделать через обычный js alert. Но мне нравиться красивый вариант http://t4t5.github.io/sweetalert/

**Comment by Golenzovskiy** [comment]
974ee0026688e03f69123c71ab1f505f48328f8b
