### ISSUE TITLE
Добавить тулбар для проекта

### ISSUE THREAD

**Issue by sintsov** [SGolenzovskiy/twbs#2]
Согласно постановки задачи требуется разместить чекбокс "Добавить описание к формулировкам" в раскрыаающимся списке референций.

![image](https://cloud.githubusercontent.com/assets/7813708/16532612/ac934eaa-3fdb-11e6-8ee0-7591b4f3cab1.png)

Думаю можно разместить его например справа в верхнем углу, поскольку нам потребуется еще возможность отсюда перейти к редактированию проекта, то предлагаю оформить какой то тулбар справа с иконками. Одна иконка для редактирования проекта, а другая как раз для копирования описания к формулировкам.

**Comment by Golenzovskiy** [comment]
c9955e6
