### ISSUE TITLE
Вынести js в отдельный файл + перенести js в футер

### ISSUE THREAD

**Issue by sintsov** [SGolenzovskiy/twbs#4]
Писал коммент про то, что надо вынести код в отдельный файл в коммитах.

Тоже самое надо сделать для датапикера + все js подключаем в футере.

**Comment by Golenzovskiy** [comment]
https://github.com/SGolenzovskiy/twbs/commit/357ae6bd8365f6958a8a3128301eeef51c5dd2bb
