### ISSUE TITLE
Добавить лоадер

### ISSUE THREAD

**Issue by sintsov** [SGolenzovskiy/twbs#5]
Есть множество сервисов позволяющих получить и настроить визуально лоадеры. Нам для проекта потребуется один какой то вариант подходящий по стилю.
http://preloaders.net/ru
https://www.sitepoint.com/online-loading-ajax-spinner-generators/

тут кстати есть знакомый тебе до глубины души лоадер http://preloaders.net/ru/rectangular
найди его :)

а еще я бы сделал для кнопки магию http://codepen.io/jmalatia/pen/HkmaA
а вот тут есть даже готовый плагин https://github.com/msurguy/ladda-bootstrap

возможно даже два лоадера избыточно и хватило бы одного на кнопку - надо смотреть

**Comment by Golenzovskiy** [comment]
https://github.com/SGolenzovskiy/twbs/commit/357ae6bd8365f6958a8a3128301eeef51c5dd2bb
