### ISSUE TITLE
Поля в поиске нужно привести в соответствие с тз

### ISSUE THREAD

**Issue by sintsov** [SGolenzovskiy/twbs#6]
Согласно обновленному ТЗ, должны быть только вот эти поля:
![image](https://cloud.githubusercontent.com/assets/7813708/16563506/32d3f5a6-420b-11e6-8833-b85acbb910b1.png)

**Comment by Golenzovskiy** [comment]
https://github.com/SGolenzovskiy/twbs/commit/f78cdd306d7a80131f800ed70010478cbb764433
