### ISSUE TITLE
Облако тегов

### ISSUE THREAD

**Issue by sintsov** [SGolenzovskiy/twbs#7]
Согласно требованию заказчика, после того как в фильтре были выбраны значения и нажата кнопка фильтрации. Между блоком фильтра и результатом выдачи, должен быть блок содержащий набор тегов. Сейчас мы просто пилим UI этого блока.

А с точки зрения реализации в этот блок будут выводиться все теги из найденых проектов, это нужно чтобы заказчик мог сузить поиск кликнув на тег, и тем самым оставив только связанные с ним проекты.

**Comment by Golenzovskiy** [comment]
https://github.com/SGolenzovskiy/twbs/commit/c5627fc39a26ec6e4057add037316271e7593315

**Comment by sintsov** [comment]
что то мне твое облако не понравилось)
во-первых перестало работать скрытие ))
во-вторых они должны быть как бы ссылками или кнопками
так как нужно фильтровать по ним
в третьих лучше чтобы этот блок жил отдельно от результатов

**Comment by Golenzovskiy** [comment]
https://github.com/SGolenzovskiy/twbs/commit/168c1fb311e11cf370157704f01e9bf930b5a819

**Comment by sintsov** [comment]
Отдельным блоком - ок. Мне кажется так более правильно с точки зрения восприятия.
Замечания:
- я бы увеличил расстояние между тегами, а то они слиплись и совсем не кажется, что это вообще теги.
- я бы теги делал бы не кнопкой а просто ссылкой
  например так:
  ![image](https://cloud.githubusercontent.com/assets/7813708/16597547/2f1056ec-4302-11e6-9769-5c21fcb555b1.png)

либо использовать лейблы, что мне кажется более уместно
![image](https://cloud.githubusercontent.com/assets/7813708/16597552/3bb55410-4302-11e6-8be6-dc6943dea4f1.png)

**Comment by Golenzovskiy** [comment]
https://github.com/SGolenzovskiy/twbs/commit/80851aa116625cbca9f4b631eb6a7420d449f9e6
