### ISSUE TITLE
Ошибка js: Uncaught ReferenceError: data is not defined

### ISSUE THREAD

**Issue by sintsov** [SGolenzovskiy/twbs#8]
![image](https://cloud.githubusercontent.com/assets/7813708/16597418/793ed53c-4301-11e6-83d5-dfd5ca0173d2.png)

**Comment by Golenzovskiy** [comment]
https://github.com/SGolenzovskiy/twbs/commit/0ab641c1aa870dd3f16b0caa07f9c236352989ba
